#!/bin/bash
COMPAREWITH=${BRANCH:-master}

CURRENT=`git log -n1 HEAD~1 | head -n1 | cut -d" " -f2`
git checkout -f $CURRENT
NEXT=`git log --reverse --ancestry-path HEAD..${COMPAREWITH} | head -n1 | cut -d" " -f2`


git reset --hard $NEXT
git reset --soft $CURRENT
git reset HEAD
